project:
  type: website

website:
  title: "Pranjul Garg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: projects.qmd
        text: Projects
      
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



